Use ExceptHandler.name instead of deprecated "identifier" (#261)
This resolves the following deprecation warning:

    .../pytest_accept/assert_plugin.py:129: DeprecationWarning:
    ExceptHandler.__init__ got an unexpected keyword argument
    'identifier'. Support for arbitrary keyword arguments is deprecated
    and will be removed in Python 3.15.

Related to #260.